# Generated by Django 6.0.3 on 2026-04-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='reorder_level',
            field=models.IntegerField(default=10),
        ),
    ]
