# Generated by Django 6.1.1 on 2026-10-03 05:30

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_medicine_batch_number_medicine_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Cost price cannot be negative."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.01, message="Price must be greater than 0."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="reorder_level",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Reorder level cannot be negative."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="stock_quantity",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Stock quantity cannot be negative."
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="medicine",
            constraint=models.UniqueConstraint(
                condition=models.Q(("batch_number__isnull", False)),
                fields=("name", "batch_number"),
                name="unique_medicine_batch",
            ),
        ),
    ]
