# Generated by Django 6.1.1 on 2026-10-03 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_medicine_cost_price_alter_medicine_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorylog",
            name="medicine_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventorylog",
            name="reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="inventorylog",
            name="stock_after",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventorylog",
            name="stock_before",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inventorylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Created"),
                    ("UPDATE", "Updated"),
                    ("DELETE", "Deleted"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="inventorylog",
            name="medicine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="inventory.medicine",
            ),
        ),
    ]
